Create list tool category
StartFuture/onboarding-me-on-back pull request #10
Opened 2023-08-07 05:14 UTC by NicholasDRR

2023-08-09 02:37 UTC, kilerhg approved these changes

2023-08-09 02:37 UTC, kilerhg requested changes
Resolver importação

2023-08-09 02:40 UTC, NicholasDRR commented on app/app.py
> +from app.routers.tool import router as router_tool
...

2023-08-11 01:48 UTC, Mateus-Toni approved these changes

2023-08-11 02:13 UTC, kilerhg approved these changes
LGTM!

2023-08-11 03:31 UTC, merged