Registration editing tools
StartFuture/onboarding-me-on-back pull request #11
Opened 2023-08-07 23:39 UTC by victorsousalima

2023-08-09 02:56 UTC, kilerhg requested changes
Resolver pendencias.

2023-08-09 02:56 UTC, kilerhg commented on app/dao/dao_tools.py
> +#def verify_tool_exists(tool: Tool):
what's this '-'

2023-08-09 02:56 UTC, kilerhg commented on app/schemas/tool.py
> +    #game_id:
Remover comentario

2023-08-09 02:56 UTC, kilerhg commented on requirements.txt
> +email-validator==2.0.0.post2
Essas bibliotecas estão sendo utilizadas?

2023-08-11 01:12 UTC, Mateus-Toni approved these changes

2023-08-11 01:13 UTC, Mateus-Toni approved these changes

2023-08-11 01:14 UTC, Mateus-Toni approved these changes

2023-08-11 01:15 UTC, Mateus-Toni approved these changes

2023-08-11 02:17 UTC, kilerhg approved these changes
LGTM!

2023-08-11 21:07 UTC, merged