feedback routers
StartFuture/onboarding-me-on-back pull request #29
Opened 2023-08-25 02:38 UTC by IgornTeii

2023-08-27 08:05 UTC, NicholasDRR requested changes

2023-08-27 08:05 UTC, NicholasDRR commented on app/routers/employee.py
> +def create_feedback_employee(feedback_employee: FeedBackEmployee):
Verificar se Employee existe antes de criar um feeback para ele

2023-08-27 08:05 UTC, NicholasDRR commented on app/routers/employee.py
> +    feedback_exists = verify_if_company_exists(company_id)
Alterar nome da variável. No caso seria "company_exists"

2023-08-31 22:48 UTC, NicholasDRR approved these changes

2023-08-31 22:50 UTC, Mateus-Toni approved these changes

2023-08-31 22:51 UTC, merged