feat(quiz): criando create e update para o quiz
StartFuture/onboarding-me-on-back pull request #9
Opened 2023-08-04 05:16 UTC by NicholasDRR

2023-08-05 00:31 UTC, kilerhg requested changes
Correções de boas praticas, e variáveis chumbadas na aplicação

2023-08-05 00:31 UTC, kilerhg commented on app/schemas/alternative.py
> +    is_answer: int
Colocar field com opção apenas para 0 ou 1

2023-08-05 00:31 UTC, kilerhg commented on app/dao/dao_quiz.py
> +    query = f'SELECT * FROM Alternative WHERE alternative_text = "{alternative.text}"'
Colocar quais colunas quer buscar no select, nunca utilizar o "*" na aplicação, somente em teste no banco direto ;)

2023-08-05 00:31 UTC, kilerhg commented on app/dao/dao_quiz.py
> +    query = f'SELECT * FROM Quiz WHERE title = "{quiz.title}"'
Colocar quais colunas quer buscar no select, nunca utilizar o "*" na aplicação, somente em teste no banco direto ;)

2023-08-05 00:31 UTC, kilerhg commented on app/dao/dao_quiz.py
> +    WHERE id = 2;
o id = 2, esse 2 deveria ser uma variável na verdade não?

2023-08-05 00:31 UTC, kilerhg commented on app/dao/dao_quiz.py
> +    ('{alternative.text}', '{alternative.is_answer}', '2');
Quiz_id deveria ser variavel?

2023-08-05 00:34 UTC, NicholasDRR commented on app/dao/dao_quiz.py
> +    ('{alternative.text}', '{alternative.is_answer}', '2');
Por enquanto será assim por não ter uma função que retorna o id necessário.

2023-08-05 00:34 UTC, NicholasDRR commented on app/dao/dao_quiz.py
> +    WHERE id = 2;
Por enquanto será assim por não ter uma função que retorna o id necessário.

2023-08-06 23:24 UTC, NicholasDRR commented on app/schemas/quiz.py
> +    link_video: str
Ao invés de field acabei utilizando EmailStr do pydantic que funciona como um validador de email

2023-08-07 00:14 UTC, NicholasDRR commented on app/schemas/alternative.py
> +    is_answer: int
Feito

2023-08-07 02:55 UTC, NicholasDRR commented on app/dao/dao_quiz.py
> +    query = f'SELECT * FROM Alternative WHERE alternative_text = "{alternative.text}"'
Alterado

2023-08-07 02:55 UTC, NicholasDRR commented on app/dao/dao_quiz.py
> +    query = f'SELECT * FROM Quiz WHERE title = "{quiz.title}"'
Alterado

2023-08-08 18:46 UTC, kilerhg commented
@NicholasDRR  Resolver conflitos com a main antes de dar merge

2023-08-08 20:33 UTC, merged